### ISSUE TITLE
BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by SirRene** [bramkragten/mind#5]
Hi,

First off all thanks for this wonderfull integrations.
Since HA 0.110 this error shows up in the log files:

```
Log Details (WARNING)
Logger: homeassistant.components.binary_sensor
Source: components/binary_sensor/__init__.py:174
Integration: Binary sensor (documentation, issues)
First occurred: 1:08:05 PM (1 occurrences)
Last logged: 1:08:05 PM

BinarySensorDevice is deprecated, modify MindBinarySensor to extend BinarySensorEntity
```

As far as I can see now the integration in still working.

BR,
René

**Comment by PDXPill** [comment]
Here is the description:
https://developers.home-assistant.io/blog/2020/05/14/entity-class-names

**Comment by jaimyborgman** [comment]
@SirRene, @pdeelen
Not sure if @bramkragten is actively maintaining this addon but I've made some changes on my fork [here](https://github.com/jaimyborgman/mind).

What did I change so far:
* fixed BinarySensorDevice deprecation warning
* added more sensors
* some code improvements

What will I do next:
* driver scores
* driver ranks
* average fuel usage
* few more MLI events
* trips as well (if possible)

**Comment by SirRene** [comment]
Hi Jaimy,

Many thanks for your hint! This helps me a lot! 
I moved over to the fork you created and it works like chars. (only had to rename 1 entity: locked -> doors)

Also I see a lot more info right now. Great!!

Keep up the good work!

Rgds,
René

**Comment by PDXPill** [comment]
@jaimyborgman also thanks for the hint! i'm moved to your fork. 
Regards, 
Paul
